# lightning.pytorch==2.0.0
seed_everything: 0
trainer:
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: 'geoclip_logs'
      name: 'resnet_50_L_10'
      version: 'moco_resnet_50'
  callbacks:
   - class_path: lightning.pytorch.callbacks.ModelCheckpoint
     init_args:
       monitor: "val_loss"
       dirpath: 'models/models-resnet-50-L-10'
       save_last: true
       filename: "{epoch}-{val_loss:.2f}"
  max_epochs: 500
  min_epochs: 100
  accelerator: 'gpu'
  devices:
    - 1
  num_sanity_val_steps: 0
model:
  embed_dim: 256
  image_resolution: 256
  vision_layers: 'moco_resnet50'
  vision_width: 128
  vision_patch_size: 32
  in_channels: 12
  le_type: 'sphericalharmonics'
  frequency_num: 32
  max_radius: 0.001
  min_radius: 0.00001
  legendre_polys: 10
  harmonics_calculation: 'analytic'
  sh_embedding_dims: 40
  pe_type: 'siren'
  learning_rate: 0.0001
  num_hidden_layers: 2
  capacity: 512
  eval_downstream: false
  air_temp_data_path: '/home/calebrobinson/ssdprivate/GeoCLIP/experiments/data/air_temp_us'
  election_data_path: '/home/calebrobinson/ssdprivate/GeoCLIP/experiments/data/med_income'
data:
  data_dir: '/home/calebrobinson/ssdprivate/GeoCLIP/data/geoclip_s2'
  batch_size: 512
  num_workers: 24
  val_random_split_fraction: 0.1
  transform: 'pretrained'
watchmodel: false